Fix the error from using deprecated ActionController::Response
I was getting:

    NameError: uninitialized constant ActionController::Response
    trusty-cms/config/initializers/response_cache_timeout.rb:1:in
`<top (required)>'

which is because ActionController::Response has become
ActionDispatch::Response.