Fix failing config spec
Was failing with following error. Assuming this was a typo.

  1) Configuration of a site valid configuration is a valid site
     Failure/Error: sa
     NameError:
       undefined local variable or method `sa' for #<RSpec::ExampleGroups::ConfigurationOfASite::ValidConfiguration:0x007fe898fe8e08>
     # ./spec/features/config_spec.rb:27:in `block (3 levels) in <top (required)>'